### ISSUE TITLE
Conceal hidden files/folders

### ISSUE THREAD

**Issue by salomonsk8r2003** [Angads25/android-filepicker#10]
I would message you if I knew how to :( I am not sure if this is the appropriate place to do this. I am new to github.

Is there a way to set a property to not show hidden files? My users are not so 'tech-savy' and when they see the dialog open with so many files starting with a period they have a hard time finding their files.

Is there already a way to adjust this?

**Comment by imGurpreetSK** [comment]
Hi @salomonsk8r2003 
I guess the hidden folders are not shown to the user by-default. You can try the following to check: Settings icon -> Appearance -> Show hidden files -> uncheck. Then, click "Clear" next to "Clear custom directory settings". Then, go back twice and the hidden .

**Comment by singhangadin** [comment]
For a quick fix, in class [ExtensionFilter](https://github.com/Angads25/android-filepicker/blob/master/filepicker/src/main/java/com/github/angads25/filepicker/utils/ExtensionFilter.java#L51) just at this method before line 51.

`if (file.getName().startsWith(".")) {
    return false;
}`

It will ignore all the directories and files starting with '.' .
In linux, hidden files and directory names start with '.' symbol.
You have to clone the project locally and then import the filepicker library as a module.

**Comment by salomonsk8r2003** [comment]
Thanks guys I appreciate the help. I am having a problem though. I am not the most experienced programmer and I can't seem to figure out how to load a library any way other than through the gradel.build "compile" statement. I tried the other day so I could edit a few things like this but I just didn't know enough to get it to work. I don't know how to make a library and don't know how to compile it into something that I can add to my project :(
