### ISSUE TITLE
Animations and Theme

### ISSUE THREAD

**Issue by salomonsk8r2003** [Angads25/android-filepicker#11]
After switching to 1.0.3 I think I might switch back to 1.0.2. The animations are a bit too much. They definitely look cool, but my users aren't going to like it. It's hard to scroll quickly and find things and my app needs quick lookups :-/

Also when you select a file and stuff starts flying all over the screen it is too much. It almost looks like a glitch. Is it supposed to be doing all that just from hitting a checkbox? Is there a way for me to make just the check box "check" and "uncheck" without anything else moving?

One final question; can I change the colors? I need to make them match my app.

Thanks Angad.

**Comment by singhangadin** [comment]
For Animation, you can simple replace existing animation with your own, just make anim directory and create two animations: 
1. marked_item_animation.xml: for marked list items
2. unmarked_item_animation.xml: for unmarked list items

For Colors, you can replace header color by defining `<color name="colorHeader">"your hex color code"</color>` in app's colors.xml remaining widgets take colors from the theme.

**Comment by salomonsk8r2003** [comment]
When I import the library through the build.gradle it puts the library in an external library and doesn't let me change it. Do I need to open your library as a separate Android Studio project, edit it, re-build it and then do something with it to get it back in my project? I could bring this question to Stack Exchange if this is not the right place to ask this.

**Comment by singhangadin** [comment]
Yup, you will get plenty of answers regarding this on stackoverflow.
