### ISSUE TITLE
Add more customize display item values 

### ISSUE THREAD

**Issue by webserveis** [Angads25/android-filepicker#12]
It would be interesting to add personalization in the first and second line, showing the size or by a text pattern with variables:
%size% %size_b% %size_kb% %size_mb% %size_gb%...
%lastmod_24% %lastmod_12%
%path%
%name%

Sample:
app:patternFirstLine="%name%
app:patternSecondLine="%size_mb% - %lastmod_24h%
app:patternTime = "YYY/mm/dd"

**Comment by singhangadin** [comment]
Ok, I will work on it in upcoming release.....Thanks.
