### ISSUE TITLE
Selecting a directory returns zero length array

### ISSUE THREAD

**Issue by zipswich** [Angads25/android-filepicker#13]
The following code is used to select a directory:

```
DialogProperties properties=new DialogProperties();
properties.selection_mode= DialogConfigs.SINGLE_MODE;
properties.selection_type=DialogConfigs.DIR_SELECT;
properties.root=new File(DialogConfigs.DEFAULT_DIR);
properties.extensions=null;
fd = new FilePickerDialog(SettingsActivity.this, properties);
fd.setDialogSelectionListener(new DialogSelectionListener() {
    @Override
    public void onSelectedFilePaths(String[] files) {
        if(files == null){
            utility.doNothihng();
        }else if(files.length == 1){
            String sPathFolder = files[0];
        }
    }
});
fd.show();
```

The result is that files.length = 0.  The selected folder is Download.

BTW, thanks a lot for this great tool.

**Comment by singhangadin** [comment]
Hey, make sure you check atleast one directory in Downloads directory, length 0 means you didn't selected any....

**Comment by zipswich** [comment]
Thank you for the tip.
I have just tried to move the focus to Download, the click Select, but got the same result.

**Comment by singhangadin** [comment]
Select button has a counter, ie. when a directory is checked, the select button text would look like select(1)... , is the text changing accordingly?

**Comment by zipswich** [comment]
Sorry, it was my misunderstanding.
I was using a D-pad to move the focus.  I have just realized that I need to click the checkbox with a mouse or using a touchscreen. 
Thanks a lot for everything. It is a very nice utility.  I would be nice to to make it D-pad utility. The users of an app (sort of TV style) primarily use D-pads for controls. Can the checkboxes be made focusable?

**Comment by singhangadin** [comment]
Thank you @zipswich, I am definitely going to look into this. Thanks a lot for sharing knowledge.!

**Comment by zipswich** [comment]
I can understand that it is challenging to accommodate both touchscreen and D-pad.
D-pad needs android:focusableInTouchMode="true", but this will make touch-screen users have to touch it twice to check it - first to focus on it, second to check it.   There may be a way to address this dilemma. 
Thank you again.  Sorry for opening this issue due to my misunderstanding.  You could close it now.
