### ISSUE TITLE
setTitle Discussion #2

### ISSUE THREAD

**Issue by willemevenwel** [Angads25/android-filepicker#14]
Hi,

I'm referring to the text that reads "sdcard/sdcard", it would be nice to
prompt the user to e.g. "Please select file(s) or directory" or "Please
select your profile data?".

See image (current):
https://imagebin.ca/v/2uU9uuc1iRzU

Prospected scenario:
https://imagebin.ca/v/2uUA7iGq6pSq

Also is there a way to turn off the animation?

Kind Regards,

WIllem

**Comment by singhangadin** [comment]
Resolved in v1.0.5: Check setTitle method.
