### ISSUE TITLE
Attribute title conflict with Android Toolbar

### ISSUE THREAD

**Issue by willemevenwel** [Angads25/android-filepicker#15]
Hi,

Thanks for previous updates.

Currently theres a conflict with the title attribute on FilePickerPreference, I refer to the following compilation error:

Error:(271) Attribute "title" has already been defined
Error:Execution failed for task ':app:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Applications/Android/sdk/build-tools/23.0.3/aapt'' finished with non-zero exit value 1

This seems to be an internal Android flaw as mentioned here:
http://stackoverflow.com/questions/18617413/attribute-title-has-already-been-defined-after-adding-after-adding-android-s

I think the conflict is because I am using android.support.v7.widget.Toolbar.

Please assist in getting a work around going.

Kind Regards

Willem

**Comment by singhangadin** [comment]
Resolved in v1.0.6, attribute is renamed to title_text.
