### ISSUE TITLE
OnCancelListener is not called

### ISSUE THREAD

**Issue by zipswich** [Angads25/android-filepicker#17]
Code:

```
myFilePickDialog.setOnCancelListener(new DialogInterface.OnCancelListener() {
    @Override
    public void onCancel(DialogInterface dialogInterface) {
        ...
    }
});
```

It does not seem to be called when Cancel is selected..

**Comment by singhangadin** [comment]
You can use a Dismiss listener instead of cancel listener. The dialog is dismissed when cancel button is pressed. [See here](https://github.com/Angads25/android-filepicker/blob/master/filepicker/src/main/java/com/github/angads25/filepicker/view/FilePickerDialog.java#L111).
