### ISSUE TITLE
The new color of fonts is too dark to allow easy reading

### ISSUE THREAD

**Issue by zipswich** [Angads25/android-filepicker#19]
The latest version's font color does not have sufficient contrast to be seen easily.

**Comment by singhangadin** [comment]
Can you provide with a screenshot?

**Comment by singhangadin** [comment]
The color scheme is theme based. See [here](https://github.com/Angads25/android-filepicker/blob/master/filepicker/src/main/res/layout/dialog_file_list_item.xml#L38) and [here](https://github.com/Angads25/android-filepicker/blob/master/filepicker/src/main/res/layout/dialog_file_list_item.xml#L45). So changing textview color in your theme will change the text color.
