### ISSUE TITLE
No path return when I use DIR_SELECT

### ISSUE THREAD

**Issue by einverne** [Angads25/android-filepicker#2]
I have these config:

```
                DialogProperties properties = new DialogProperties();
                properties.selection_mode = DialogConfigs.SINGLE_MODE;
                properties.selection_type = DialogConfigs.DIR_SELECT;
                properties.root = new File("/sdcard/facedetect");
                properties.extensions=null;

                FilePickerDialog dialog = new FilePickerDialog(MainActivity.this, properties);
                dialog.setDialogSelectionListener(new DialogSelectionListener() {
                    @Override
                    public void onSelectedFilePaths(String[] files) {

                    }
                });
                dialog.show();
```

I have noticed that if I use `DIR_SELECT` , I cannot get the path from `String[] files`. Following is the screenshot

![image](https://cloud.githubusercontent.com/assets/1962738/17392493/4fe57c16-5a50-11e6-9824-46230257c801.png)
#

**Comment by singhangadin** [comment]
Can you see check boxes for selecting directories?

**Comment by singhangadin** [comment]
I think you might have forgotten to set fileselectlistener to the dialog

**Comment by einverne** [comment]
I have set the listener, and I cannot get any value for the listener callback. If I use DIR_SELECT  I cannot even see checkbox. And I cannot even change my root dir.

**Comment by singhangadin** [comment]
You have not setProperties of dialog either through constructor or functions. Which is the reason why you are getting default configurations....

**Comment by einverne** [comment]
I have updated my problem.

**Comment by singhangadin** [comment]
Is there any sub directory in '/sdcard/facedetect' directory? and does '/sdcard/face' directory exist?

**Comment by einverne** [comment]
Yes, it exist.

**Comment by singhangadin** [comment]
Is facedetect empty?

**Comment by einverne** [comment]
In my demo, fecedetect is not empty. Can I get the root folder path I choose in call function? Or I can only get the file path I choose?

**Comment by einverne** [comment]
OK, I got it. If I choose to set the root, I cannot go up to it's parent folder. I have solved it. And I can  only get the path I choose using the checkbox. I was thinking that if I didn't choose anything, the lib will return the root folder path.

And by the way, really thanks for your work.
