### ISSUE TITLE
How to hide check boxes for all files in single mode

### ISSUE THREAD

**Issue by saibbyweb** [Angads25/android-filepicker#21]
Even in single mode, check boxes are visible for all files. It gives a feel of being in multi-mode. Is there any way to hide check boxes and let user select the file only on clicking it for (single mode).

**Comment by singhangadin** [comment]
Not possible yet.

**Comment by dbrgn** [comment]
That's also something I'm looking for. Would be great if there were a mode that allows you to tap on a filename to select it and close the dialog directly.

**Comment by zoff99** [comment]
#29
