### ISSUE TITLE
File name animation while scrolling

### ISSUE THREAD

**Issue by AljosaH** [Angads25/android-filepicker#23]
Hi
I really like your filepicker. It's simple to integrate and works without issues.
However there is one thing that's bothering me - the right-to-left animation of icons and file names while scrolling up or down. It does look nice and smooth, but it kind of doesn't fit in my app. My app is quite static and to suddenly have everything moving is a bit annoying.
Is there a simple way of switching these animations off?
Thanks.

**Comment by singhangadin** [comment]
Hi, I have mentioned [here](https://github.com/Angads25/android-filepicker/wiki/styles-and-animations#animations) regarding how to put your own animation. You can try this with a blank animation.

**Comment by AljosaH** [comment]
Wow. Nice. Sorry, I somehow missed that part of Wiki.
Worked like a charm, of course.
Thank you!
