### ISSUE TITLE
Seemed there was a bug when selecting the file

### ISSUE THREAD

**Issue by nanangarsyad** [Angads25/android-filepicker#25]
could you please help me, 
when I tried to select a file from the dialog file-listing it seemed a bit  unresponsive.

here is the screenshot.

![ezgif-632323787](https://cloud.githubusercontent.com/assets/7588442/20251230/3cc86464-aa4a-11e6-8250-f532fc992f2d.gif)

and another question, is it possible to disable the animation when selecting files (the fly-in animation)?
and I also I want to make the selection by clicking the list item instead of the checkbox

Thank you

**Comment by singhangadin** [comment]
Please refer to issue [23](https://github.com/Angads25/android-filepicker/issues/23) for removing animation. As of checkbox bug, i think i would still be needing some time to fix it.

**Comment by singhangadin** [comment]
Hi, I have made few major changes for checkbox click issue. Will really appreciate if you could see to that and help me with bugs. Thank you.
