### ISSUE TITLE
Filetype filtering

### ISSUE THREAD

**Issue by dbrgn** [Angads25/android-filepicker#26]
Is a filter for filetypes (e.g. RegEx based) planned? I need a file picker that only shows SVG files :)

**Comment by singhangadin** [comment]
Extension filtering has been explained [here](https://github.com/angads25/android-filepicker/wiki/dialog-properties#extensions) in the Wiki. 
In reference to link above, your extension array would look like: 
String ext={"svg"};
and dialog will include only svg files.

**Comment by dbrgn** [comment]
Ah, thanks a lot! I ctrl-f-ed for "filter", that's why I didn't find it :)
