### ISSUE TITLE
Is it possible to show directiores based on the files present in it Eg show only directiories  which have pdf files

### ISSUE THREAD

**Issue by fast1234** [Angads25/android-filepicker#28]
Will it be possible to show Directory only if pdf, txt, image file is present in that folder. I mean by default it is showing system Directories as well. I need to show only those directories which have at least one of the required files like pdf,txt, image. 
I saw the Dialog properties where we can hide files other than specified in ext array passed as below.
```
 String ext[] =new String[] {"jpg","jpeg","png","gif"};
        properties.extensions=ext;
```
But here the problem I am facing is , it is still showing the folders which don't contain the above extns.

**Comment by hudmond** [comment]
It seems to me that this kind of folder iteration would be very taxing (slow) to go through each folder and check if the files are contained therein before displaying them.

**Comment by singhangadin** [comment]
It will become very difficult to optimized for nested and heavy folders.

**Comment by hudmond** [comment]
Another option for what you want to do fast1234 might be to check out the MediaStore.Files functionality of android, you could query the MediaStore.Files and find file locations that contain your particular filetype and display only those folders in a listview for the user to interact with. This is just using a sql type query and would be much faster than iterating through all of the folders. Btw Angads great library thanks for this!
