### ISSUE TITLE
如何自定义选择器界面？

### ISSUE THREAD

**Issue by sendtion** [Angads25/android-filepicker#3]
比如，我想把黑色头部设置成主题色，想把选择按钮改为删除等等。。

**Comment by singhangadin** [comment]
At present it is not available, but I am working on that....

**Comment by singhangadin** [comment]
Though you can simply replace SELECT text from button by adding:
    `<string name="choose_button_label">=Your Positive Action String=</string>`
in your Strings.xml

**Comment by sendtion** [comment]
Thanks. Come on!
