### ISSUE TITLE
didn't find how to allways set the up path

### ISSUE THREAD

**Issue by nohkumado** [Angads25/android-filepicker#32]
hello,
the path given at instantiation is the root node for the dialog, meaning you can navigate up and down from there, but you can't get up....

now i give that path, from a stored variable, so as to move the user to a section of the filesystem where his files are supposed to be....

but once set, he can't escape the actual project to go to the next.... anyway to set a top-most root and an actual position ?

**Comment by singhangadin** [comment]
I think offset property is what you have been looking for. For more info read [here](https://github.com/Angads25/android-filepicker/blob/master/filepicker/src/main/java/com/github/angads25/filepicker/model/DialogProperties.java#L62).

**Comment by zoff99** [comment]
why did you close this issue? there is now offical release yet.
how can i use it with gradle?

**Comment by singhangadin** [comment]
Version 1.0.8 is live now...

**Comment by nohkumado** [comment]
yeah! works!! thanks a lot!
