### ISSUE TITLE
FilePickerDialog->onItemClick NPE

### ISSUE THREAD

**Issue by yanchumak** [Angads25/android-filepicker#34]
`parent.setLocation(currLoc.getParentFile().getAbsolutePath());`
if there is no access to the parent directory we have NPE, because currLoc.getParentFile() return null
I do fork and commit
https://github.com/yanchumak/android-filepicker/commit/4467efd57c47cd7fde400e9543c0f2687e7af231

**Comment by singhangadin** [comment]
If you have fixed it, You can make a pull request..

**Comment by singhangadin** [comment]
There was a bug in existing code, it has been fixed for now
