### ISSUE TITLE
Changing color

### ISSUE THREAD

**Issue by mkaflowski** [Angads25/android-filepicker#38]
Hi
How to change colors or style of FilePickerDialog in code?
Getting color this way should help for changing themes:

` int[] attrs = new int[] { R.attr.colorPrimary/* index 0 */};
        TypedArray ta = obtainStyledAttributes(attrs);
        ta.getColor(0,0);
        ta.recycle();`

Thank you
Love that lib :)

**Comment by singhangadin** [comment]
Use following code to change header color. Colors used in library can be found [here](https://github.com/Angads25/android-filepicker/blob/master/filepicker/src/main/res/values/colors.xml).
`<color name="colorHeader">"Header Color code"</color>`
