### ISSUE TITLE
header text background

### ISSUE THREAD

**Issue by monolifed** [Angads25/android-filepicker#39]
For some reason if I set the background color in my app, header looks weird (filepicker/src/main/res/layout/dialog_header.xml).

**Comment by singhangadin** [comment]
Can you upload a screenshot?

**Comment by monolifed** [comment]
![pic](https://i.imgur.com/eENYpSA.png)

**Comment by monolifed** [comment]
```
<resources>
    <!-- Base application theme. -->
    <style name="MyTheme" parent="android:Theme">
        <item name="android:textViewStyle">@android:style/Widget.TextView</item>
        <item name="android:textAppearance">@android:style/TextAppearance</item>
        <item name="android:textAppearanceLarge">@android:style/TextAppearance.Large</item>
        <item name="android:background">#F00</item>
    </style>
</resources>
```

**Comment by singhangadin** [comment]
Most components of Dialog are using default background attribute. In the above mentioned theme you are using `<item name="android:background">#F00</item>` which changes default background to Red. That is why most of the components that use default background ([List Item](https://github.com/Angads25/android-filepicker/blob/master/filepicker/src/main/res/layout/dialog_file_list_item.xml#L10), TextView, ImageView) have Red background.

**Comment by singhangadin** [comment]
It will work fine if you add another style constraint to change TextView background color to transparent(@null).

**Comment by monolifed** [comment]
Items work as I expected but the header still doesn't look right.

![not working](https://i.imgur.com/RW6tfTE.png)

```
<resources>

    <!-- Base application theme. -->
    <style name="MyTheme" parent="android:Theme">
        <item name="android:textViewStyle">@style/MyTextViewStyle</item>
        <item name="android:textAppearance">@style/MyTextAppearance</item>
        <item name="android:textAppearanceLarge">@style/MyTextAppearanceLarge</item>
        <item name="android:background">#F00</item>
    </style>

    <style name="MyTextViewStyle" parent="android:Widget.TextView">
        <item name="android:textColor">#FFF</item>
        <item name="android:background">#F0F</item>
    </style>

    <style name="MyTextAppearance" parent="@android:style/TextAppearance">
        <item name="android:textColor">#CCC</item>
        <item name="android:background">#00F</item>
    </style>

    <style name="MyTextAppearanceLarge" parent="@android:style/TextAppearance.Large">
        <item name="android:textColor">#000</item>
        <item name="android:background">#0F0</item>
    </style>

</resources>
```

**Comment by singhangadin** [comment]
I made few changes and here is the final result...
![device-2017-03-12-192419](https://cloud.githubusercontent.com/assets/7099405/23832416/9008ee0c-0759-11e7-8e36-c3a9987f03d3.png)

**Comment by monolifed** [comment]
Although, I can't see the changes you have made, it looks right.

**Comment by singhangadin** [comment]
I have committed changes in Github repository, you can verify by cloning module in your project. I will publish a release once problem is fixed.
