### ISSUE TITLE
setTitle is not wotking

### ISSUE THREAD

**Issue by acarmon** [Angads25/android-filepicker#4]
It's an excellent filepicker but i can't set a title for the filepicker dialog

**Comment by singhangadin** [comment]
The dialog doesn't have title, you can see that in second line of oncreate method in filepickerdialog class.(https://github.com/Angads25/android-filepicker/blob/master/filepicker/src/main/java/com/github/angads25/filepicker/view/FilePickerDialog.java)

**Comment by singhangadin** [comment]
I will release an update soon with Title....

**Comment by willemevenwel** [comment]
Hi,

Thanks for a wonderful library. This is especially cool for phones on which opening intent type "_/_" or "file/*" does not work.

I would like to know if setTitle has been added to the latest com.github.angads25:filepicker:1.0.3?

Regards

Willem

**Comment by singhangadin** [comment]
Hi, I have consulted few Android Designers regarding this issue, according to them the dialog already has a toolbar(header) and wrapping it inside the titled dialog would be a bad designing practice. Also, toolbar is used as the header of dialog, so apparently it won't be possible to show title as one of them has to be removed, either title or header.

**Comment by willemevenwel** [comment]
Hi,

I'm referring to the text that reads "sdcard/sdcard", it would be nice to
prompt the user to e.g. "Please select file(s) or directory" or "Please
select your profile data?".

See image (current):
[image: Inline image 1]

Prospected scenario:
[image: Inline image 2]

Also is there a way to turn off the animation?

Kind Regards,

WIllem
