### ISSUE TITLE
Use colors from current theme

### ISSUE THREAD

**Issue by alexeyvasilyev** [Angads25/android-filepicker#41]
At the moment the library does not use colors for current app theme.
If I have the following theme assigned to the app
```
<resources>
    <style name="AppTheme.Dark.Cyan" parent="AppTheme.Dark">
        <item name="colorAccent">@color/material_cyan_300</item>
    </style>
</resources>
```

then filepicker still needs colorAccent in colors.xml to override button text.
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="colorAccent">#ff9800</color>
<resources>
```

Check how this is done in android.support.v7.app.AlertDialog.

**Comment by SylvainPoree** [comment]
To help users of you Dialog dealing with the theme, you could as well simply implement a constructor of FilePickerDialog that gets the parameters of Dialog : public Dialog(@NonNull Context context, @StyleRes int themeResId) si that they can modifiy the theme.
Very simple to put in place : add this constructor : 
public FilePickerDialog(Context context, DialogProperties properties, @StyleRes int themeResId) {
        super(context, themeResId);
        this.context = context;
        this.properties = properties;
        filter = new ExtensionFilter(properties);
        internalList = new ArrayList<>();
    }
and it's done !

**Comment by singhangadin** [comment]
@SylvainPoree I really appreciate your effort for helping out with this issue, Since very beginning customization and theming are the things I have been thinking to improve.

**Comment by alexeyvasilyev** [comment]
The issue still not fixed.
I can change text size via custom theme, however colorAccent is not used by theme provided via FilePickerDialog(Context, DialogProperties, @styleres int) constructor.

**Comment by esunilkumare** [comment]
@alexeyvasilyev 

Just add below colors in your color.xml file

<color name="colorPrimary">your_color</color>
<color name="colorPrimaryDark">your_color</color>
<color name="colorAccent">your_color</color>

It will override the file_picker colors_
