### ISSUE TITLE
Return Directory Without Checkbox

### ISSUE THREAD

**Issue by rayliverified** [Angads25/android-filepicker#44]
I am using the FilePicker as a download file path selector. The user navigates to the directory they would like to save their files in and selects that folder. However, in the current implementation, that behavior does not work. Instead, the user is required to select their desired directory using the checkbox button. 

I think that the library should return the file path the user navigated to without the checkbox requirement.

**Comment by rayliverified** [comment]
Also, it would be a great enhancement if the library could remember the last selected location and open to that location. Probably possible to do this using SharedPreferences.

**Comment by npes87184** [comment]
Hi, @searchy2 

I have push a commit for first request. If you can not wait for @Angads25 merge or anymore, you can build it yourself.

The second problem, it should be implemented in the app of users, IMO.

Cheers!

**Comment by rayliverified** [comment]
@npes87184 That's awesome! Thanks for implementing this feature and sharing with the community :hugs: 
I tried looking into the code and giving it a go myself but other things came up. Hopefully it wasn't too difficult for you!

You are absolutely right about the second problem. I think storing the last file path in a shared preferences file would do the trick.

**Comment by npes87184** [comment]
Hi, @searchy2 

What things do you meet?

Thanks.

**Comment by rayliverified** [comment]
@npes87184 I use the library for a path selector in my apps. For example, I give users the ability to choose where they would like to save downloaded photos or media files. What do I need from this library? Nothing more! With your implementation, it contains everything I require.
