### ISSUE TITLE
Select button active when no files are selected

### ISSUE THREAD

**Issue by blady214** [Angads25/android-filepicker#59]
Hi!

I found out a little bug in the file picker. If you will select file and then reopen file picker it lets you to click _Select_ button even if no file or directory has been selected.

**Comment by singhangadin** [comment]
Hey, Do you create a new dialog on every event, or use an existing one?

**Comment by blady214** [comment]
Hey, now I am creating new dialog everytime becaues I found out that this is workaround for my issue. If I will use again previously created dialog I raise the issue.
