### ISSUE TITLE
Text color in File picker isn't correct

### ISSUE THREAD

**Issue by qbait** [Angads25/android-filepicker#60]
It looks like that in my case. I've tried to inject theme without a success.
`        mFilePickerDialog = new FilePickerDialog(getContext(), properties, android.R.style.Theme_Holo);
`
Which resource is used for a text color?

https://www.dropbox.com/s/s21wzls4l1vdz3d/Screenshot_20170901-151606.png?dl=0

**Comment by OmarAliSaid** [comment]
dialog = new FilePickerDialog(your acctivity , properties , android.R.style.Theme_Holo_Light);
