### ISSUE TITLE
canceListener does not work

### ISSUE THREAD

**Issue by omidaminiva** [Angads25/android-filepicker#61]
I have an activity that if user taps on cancel I like to call finish(); but when tap on cancel button

```
dialog.setOnCancelListener(new DialogInterface.OnCancelListener() {
                @Override
                public void onCancel(DialogInterface dialog) {
                    
                }
            });
```
does not work, I also tried

`dialog.findViewById(R.id.cancel).setOnClickListener`
but get dialog.findViewById(R.id.cancel) is null

the only thing works is

` dialog.setOnDismissListener`
but that is working if user presses submit and cancel. So I would not know which one is pressed.

**Comment by singhangadin** [comment]
Hey, I think you are looking for a way to differentiate between a select and a cancel dismiss, for which you can also check what was the size of file path array in callback. Size zero is a cancel and selection in all other cases.

**Comment by omidaminiva** [comment]
right and that is good work around. but if we call cancel on cancel and dismiss on dismiss listener work properly. please have a look at my pull request
