### ISSUE TITLE
How can we set the required file extension in this lib?

### ISSUE THREAD

**Issue by mkamals1989** [Angads25/android-filepicker#63]
Hi,

I want to know can we set only the required file format in this lib. I want to pick only images,pdf, doc and txt file so users cannot see other files.

I came across extension field in DialogProperties, can i set the extension in the below format?
 DialogProperties properties = new DialogProperties();
                properties.selection_mode = DialogConfigs.SINGLE_MODE;
                properties.selection_type = DialogConfigs.FILE_SELECT;
                properties.root = new File(DialogConfigs.DEFAULT_DIR);
                properties.error_dir = new File(DialogConfigs.DEFAULT_DIR);
                properties.offset = new File(DialogConfigs.DEFAULT_DIR);
                **properties.extensions = new String[]{"pdf", "txt", "doc", "image"};**

Thanks & Regards,
Kamal S

**Comment by singhangadin** [comment]
Library doesn't support mime types by now, you have to individually specify all the extensions.

**Comment by mkamals1989** [comment]
Ok, I am asking how to specify the extension?
