### ISSUE TITLE
nullpointer on dir select

### ISSUE THREAD

**Issue by janvde** [Angads25/android-filepicker#7]
I am on version 1.02 and still getting a null pointer exception when I try to choose a directory: 

`java.lang.NullPointerException
                                                                            at com.github.angads25.filepicker.view.FilePickerDialog$1.onClick(FilePickerDialog.java:100)`

This is my code: 

DialogProperties properties = new DialogProperties();

```
        properties.selection_mode = DialogConfigs.SINGLE_MODE;
        properties.selection_type = DialogConfigs.DIR_SELECT;
        properties.root = new File(DialogConfigs.STORAGE_DIR);
        properties.extensions = null;
        FilePickerDialog dialog = new FilePickerDialog(getActivity(), properties);
        dialog.setDialogSelectionListener(new DialogSelectionListener() {
            @Override
            public void onSelectedFilePaths(String[] files) {
                Log.d(TAG, "onSelectedFilePaths: " + files.length);
                if (files.length > 0) {
                    //stuff
                }
            }
        });
        dialog.show();`
```

**Comment by singhangadin** [comment]
Is it specific to an Android version or is with all in all above 9?

**Comment by janvde** [comment]
This was on api level 19, on a Nexus 7 (emulator).

**Comment by singhangadin** [comment]
I have tried this code in my phone and its working, are you able to see the dialog and files? or is it crashing without showing dialog.

**Comment by janvde** [comment]
I am able to see the dialog and files, but when I select one of the checkboxes and tap the select(1) button, it crashes with the above nullpointer exception.

**Comment by singhangadin** [comment]
Hi, just wanted to know if you have found something regarding issue? Because I have tested it in emulator and it is working.
