### ISSUE TITLE
Can't grant the permission (Screen Overlay Detected)

### ISSUE THREAD

**Issue by gerosyab** [Angads25/android-filepicker#8]
When I tried to grant the storage permission, android system's dialog is poped.

It says "Screen overlay detected - To change this permission setting you first have to turn off the screen overlay from Settings > Apps".

Usually this problem is caused by screen filter application but I don't use any of them.

Anyway I found that is caused by toast message.
[ FilePickerDialog.onShow() - Line203]
`Toast.makeText(context,"Application needs you permission to access SD Card",Toast.LENGTH_LONG).show();`

If I wait until the message disappears then I can get the app's storage permission.

Different method would be necessary to inform about permission.

**Comment by singhangadin** [comment]
OK, I ll see into that and will definitely fix it in next release....

**Comment by ghost** [comment]
Toast should be removed from this code I think:
```
@Override
    public void show() {
        if(!Utility.checkStorageAccessPermissions(context))
        {   if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                //TODO: Overlay Issue's Cause
                Toast.makeText(context,"Application needs you permission to access SD Card",Toast.LENGTH_LONG).show();
                ((Activity)context).requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE}, EXTERNAL_READ_PERMISSION_GRANT);
            }
        }
        else
        {   super.show();
        }
    }
```

**Comment by zaferertas** [comment]
Hello Angads,
I have put your library in my live app. Appreciate if you can fix this error asap. As mentioned above, the Toast is causing the issue. 
Thanks in advance.

**Comment by singhangadin** [comment]
Hi @zaferertas, I apologise for inconvenience library has been causing to you. The issue has been caused by toast as it is covering the dialog. As of now you can clone and import this module and it will work fine by simply commenting that toast message.

**Comment by singhangadin** [comment]
Unfortunately, I cannot fix it myself for quite awhile. But I will fix it ASAP and I assure you it is the first thing I will work on. I will be more than happy if you could fix this for me with an alternative.
