### ISSUE TITLE
Choosing directories

### ISSUE THREAD

**Issue by dbognar** [Angads25/android-filepicker#84]
Thank you for your great work on this file picker, this is the best I've seen yet.

My issue:
I have an app specific export directory and I have my offset right there, but the user can not export the file directly there, just if he gets back, search for that particular directory, then check it. I think it would be a great addition, if you can configure directory selection to a mode, where the select button is always on, and when you touch it, it will give you back the actual path.

(or a more simple approach: make select available, when there are no more sub-directories in your directory list, and give back the actual path)

Also I think it would be useful to see the files in directory selection mode. Because when I'm exporting a file I would like to see what kind of files are there in the selected directory.

**Comment by Skyost** [comment]
:+1:

**Comment by npes87184** [comment]
Hi, @dbognar 

Reference to issue #44 
And there is a [patch](https://github.com/npes87184/android-filepicker/commit/c82630a30a72ca120548db1072b2f9c540860bef) in my repo which can support it.

Thanks.

**Comment by dbognar** [comment]
Thank you! I'm new on GitHub, how can i implement it? I'm currently using this Filepicker as a compile dependency. (maven central)

**Comment by npes87184** [comment]
Hi, @dbognar 

There is a pre-built aar in [my repo](https://github.com/npes87184/S2TDroid/blob/pro/app/libs/filepicker-release.aar), and you can follow this [file](https://github.com/npes87184/S2TDroid/blob/pro/app/build.gradle) to use.

Shortly, it should create libs directory to hold aar and add these two lines in build.gradle
```
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation(name: 'filepicker-release', ext: 'aar')
```

Or aar can be built by yourself, which is via git clone the project and import it to your Android studio. After aar is built, you can follow the same steps as above to use aar. 

Thanks.

**Comment by dbognar** [comment]
Thank you, everything works fine. ;)
