### ISSUE TITLE
Checkboxes not visible unless checked

### ISSUE THREAD

**Issue by salomonsk8r2003** [Angads25/android-filepicker#9]
My users do not like the behavior of the check boxes. They do not look like the screenshots. The check boxes are invisible until checked. It actually took us a while to realize we could even touch in that area to select a file.

I recommend you make the check boxes visible even when not checked. Either that or make the selection by clicking the file, but that would mess with the directory selection. Easiest way is to make all check boxes visible.

I know how to do it, but I am not sure how to recompile the library with my changes. I messed with android studio all day today and can't figure it out.

If you do this change then I would LOVE to use your library.

EDIT:
I should probably have mentioned... GREAT WORK!!! This library is awesome either way and looks great. It will be a huge time saver for me and looks better than some other ones I have seen. Just need this ooooooone tiny thing changed.

**Comment by singhangadin** [comment]
Hi, the check box is not visible because of theming issues, however it has been fixed in version 1.0.3, are you using a version that is lower than this?

**Comment by salomonsk8r2003** [comment]
Oops I was using 1.0.2. That is what I copied from the read-me.

I'll try that out. Thank you! I tried a few other libraries and definitely like yours the best.
